# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller recipe for a fully self-contained WebM2GIF.app.

Build it with::

    .venv/bin/python tools/build_app.py --standalone

Requires ``pip install -r requirements-dev.txt`` (PyInstaller) and a network
connection, because the packaged app carries its own ffmpeg binary.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(SPECPATH).parent
sys.path.insert(0, str(PROJECT_ROOT))

from webm2gif import APP_NAME, BUNDLE_IDENTIFIER, __version__  # noqa: E402

binaries = []
datas = []

# Ship a static ffmpeg inside the bundle: ImageIO-FFmpeg provides one, and the
# resolver in webm2gif.ffmpeg looks for "<bundle>/bin/ffmpeg" first.
try:
    import imageio_ffmpeg

    binaries.append((imageio_ffmpeg.get_ffmpeg_exe(), "bin"))
except Exception:  # pragma: no cover - optional dependency
    pass

icon = PROJECT_ROOT / "build" / "AppIcon.icns"
if not icon.exists():  # pragma: no cover - generated by tools/make_icon.py
    print("警告: 未找到 build/AppIcon.icns，将使用默认图标")

analysis = Analysis(
    [str(PROJECT_ROOT / "packaging" / "entry.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=[
        "objc",
        "AppKit",
        "Foundation",
        "PyObjCTools",
        "webm2gif",
        "webm2gif.app",
        "webm2gif.cli",
        "webm2gif.ui.main_window",
    ],
    excludes=[
        "tkinter",
        "numpy",
        "pandas",
        "matplotlib",
        "PIL",
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "IPython",
        "notebook",
    ],
    noarchive=False,
)
pyz = PYZ(analysis.pure)

exe = EXE(
    pyz,
    analysis.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    codesign_identity=None,
    entitlements_file=None,
)
collection = COLLECT(
    exe,
    analysis.binaries,
    analysis.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)
app = BUNDLE(
    collection,
    name=f"{APP_NAME}.app",
    icon=str(icon) if icon.exists() else None,
    bundle_identifier=BUNDLE_IDENTIFIER,
    info_plist={
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": "WebM → GIF",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        "LSMinimumSystemVersion": "12.0",
        "LSApplicationCategoryType": "public.app-category.video",
        "NSHighResolutionCapable": True,
    },
)
