# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller recipe for a fully self-contained WebM2GIF.app.

Build it with::

    .venv/bin/python tools/build_app.py --standalone

Requires ``pip install -r requirements-dev.txt`` (PyInstaller) and a network
connection, because the packaged app carries its own ffmpeg binary.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(SPECPATH).parent
sys.path.insert(0, str(PROJECT_ROOT))

from webm2gif import APP_NAME, BUNDLE_IDENTIFIER, __version__  # noqa: E402

binaries = []
datas = []

# ffmpeg 不由这里塞进来：tools/build_app.py 会把解析到的那个可执行文件放到
# <bundle>/bin/ffmpeg，也就是 webm2gif.ffmpeg 优先查找的位置。曾经这里额外加过
# 一份 imageio-ffmpeg 的二进制，结果和 PyInstaller 自动收集的包数据叠成三份，
# 让 165 MB 的包里白白装了 141 MB 的 ffmpeg，所以去掉了。

icon = PROJECT_ROOT / "build" / "AppIcon.icns"
if not icon.exists():  # pragma: no cover - generated by tools/make_icon.py
    print("警告: 未找到 build/AppIcon.icns，将使用默认图标")

analysis = Analysis(
    [str(PROJECT_ROOT / "packaging" / "entry.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=[
        "objc",
        "AppKit",
        "Foundation",
        "PyObjCTools",
        "webm2gif",
        "webm2gif.app",
        "webm2gif.cli",
        "webm2gif.ui.main_window",
    ],
    excludes=[
        # 独立版自带 ffmpeg，不需要 imageio-ffmpeg 的包数据和它那 47 MB 的二进制；
        # webm2gif.ffmpeg 里对它的 import 包在 try/except 中，缺了也能正常回退。
        "imageio_ffmpeg",
        "tkinter",
        "numpy",
        "pandas",
        "matplotlib",
        "PIL",
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "IPython",
        "notebook",
    ],
    noarchive=False,
)
pyz = PYZ(analysis.pure)

exe = EXE(
    pyz,
    analysis.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    codesign_identity=None,
    entitlements_file=None,
)
collection = COLLECT(
    exe,
    analysis.binaries,
    analysis.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)
app = BUNDLE(
    collection,
    name=f"{APP_NAME}.app",
    icon=str(icon) if icon.exists() else None,
    bundle_identifier=BUNDLE_IDENTIFIER,
    info_plist={
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": "WebM → GIF",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        "LSMinimumSystemVersion": "12.0",
        "LSApplicationCategoryType": "public.app-category.video",
        "NSHighResolutionCapable": True,
    },
)
